insert into product(category, brand, price) values ('상의', 'A', '11200');
insert into product(category, brand, price) values ('상의', 'B', '10500');
insert into product(category, brand, price) values ('상의', 'C', '10000');
insert into product(category, brand, price) values ('상의', 'D', '10100');
insert into product(category, brand, price) values ('상의', 'E', '10700');
insert into product(category, brand, price) values ('상의', 'F', '11200');
insert into product(category, brand, price) values ('상의', 'G', '10500');
insert into product(category, brand, price) values ('상의', 'H', '10800');
insert into product(category, brand, price) values ('상의', 'I', '11400');

insert into product(category, brand, price) values ('아우터', 'A', '5500');
insert into product(category, brand, price) values ('아우터', 'B', '5900');
insert into product(category, brand, price) values ('아우터', 'C', '6200');
insert into product(category, brand, price) values ('아우터', 'D', '5100');
insert into product(category, brand, price) values ('아우터', 'E', '5000');
insert into product(category, brand, price) values ('아우터', 'F', '7200');
insert into product(category, brand, price) values ('아우터', 'G', '5800');
insert into product(category, brand, price) values ('아우터', 'H', '6300');
insert into product(category, brand, price) values ('아우터', 'I', '6700');

insert into product(category, brand, price) values ('바지', 'A', '4200');
insert into product(category, brand, price) values ('바지', 'B', '3800');
insert into product(category, brand, price) values ('바지', 'C', '3300');
insert into product(category, brand, price) values ('바지', 'D', '3000');
insert into product(category, brand, price) values ('바지', 'E', '3800');
insert into product(category, brand, price) values ('바지', 'F', '4000');
insert into product(category, brand, price) values ('바지', 'G', '3900');
insert into product(category, brand, price) values ('바지', 'H', '3100');
insert into product(category, brand, price) values ('바지', 'I', '3200');

insert into product(category, brand, price) values ('스니커즈', 'A', '9000');
insert into product(category, brand, price) values ('스니커즈', 'B', '9100');
insert into product(category, brand, price) values ('스니커즈', 'C', '9200');
insert into product(category, brand, price) values ('스니커즈', 'D', '9500');
insert into product(category, brand, price) values ('스니커즈', 'E', '9900');
insert into product(category, brand, price) values ('스니커즈', 'F', '9300');
insert into product(category, brand, price) values ('스니커즈', 'G', '9000');
insert into product(category, brand, price) values ('스니커즈', 'H', '9700');
insert into product(category, brand, price) values ('스니커즈', 'I', '9500');

insert into product(category, brand, price) values ('가방', 'A', '2000');
insert into product(category, brand, price) values ('가방', 'B', '2100');
insert into product(category, brand, price) values ('가방', 'C', '2200');
insert into product(category, brand, price) values ('가방', 'D', '2500');
insert into product(category, brand, price) values ('가방', 'E', '2300');
insert into product(category, brand, price) values ('가방', 'F', '2100');
insert into product(category, brand, price) values ('가방', 'G', '2200');
insert into product(category, brand, price) values ('가방', 'H', '2100');
insert into product(category, brand, price) values ('가방', 'I', '2400');

insert into product(category, brand, price) values ('모자', 'A', '1700');
insert into product(category, brand, price) values ('모자', 'B', '2000');
insert into product(category, brand, price) values ('모자', 'C', '1900');
insert into product(category, brand, price) values ('모자', 'D', '1500');
insert into product(category, brand, price) values ('모자', 'E', '1800');
insert into product(category, brand, price) values ('모자', 'F', '1600');
insert into product(category, brand, price) values ('모자', 'G', '1700');
insert into product(category, brand, price) values ('모자', 'H', '1600');
insert into product(category, brand, price) values ('모자', 'I', '1700');

insert into product(category, brand, price) values ('양말', 'A', '1800');
insert into product(category, brand, price) values ('양말', 'B', '2000');
insert into product(category, brand, price) values ('양말', 'C', '2200');
insert into product(category, brand, price) values ('양말', 'D', '2400');
insert into product(category, brand, price) values ('양말', 'E', '2100');
insert into product(category, brand, price) values ('양말', 'F', '2300');
insert into product(category, brand, price) values ('양말', 'G', '2100');
insert into product(category, brand, price) values ('양말', 'H', '2000');
insert into product(category, brand, price) values ('양말', 'I', '1700');

insert into product(category, brand, price) values ('액세서리', 'A', '2300');
insert into product(category, brand, price) values ('액세서리', 'B', '2200');
insert into product(category, brand, price) values ('액세서리', 'C', '2100');
insert into product(category, brand, price) values ('액세서리', 'D', '2000');
insert into product(category, brand, price) values ('액세서리', 'E', '2100');
insert into product(category, brand, price) values ('액세서리', 'F', '1900');
insert into product(category, brand, price) values ('액세서리', 'G', '2000');
insert into product(category, brand, price) values ('액세서리', 'H', '2000');
insert into product(category, brand, price) values ('액세서리', 'I', '2400');
